### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by SyedOmarNooredu** [nschloe/perfplot#112]
Running concat.py in the example folder:
```
Traceback (most recent call last):
  File "C:\Users\syedo\floobits\****\share_me\perfplot_test.py", line 6, in <module>
    perfplot.show(
  File "C:\Users\syedo\AppData\Roaming\Python\Python39\site-packages\perfplot\_main.py", line 506, in show
    out = bench(*args, **kwargs)
  File "C:\Users\syedo\AppData\Roaming\Python\Python39\site-packages\perfplot\_main.py", line 467, in bench
    timings_s[i] = next(b)
  File "C:\Users\syedo\AppData\Roaming\Python\Python39\site-packages\perfplot\_main.py", line 246, in __next__
    repeat = remaining_time_ns // t_ns`
ZeroDivisionError: integer division or modulo by zero
```
Setup:
- Python 3.9.0 64-bit
  - numpy 1.20.1
  - perfplot 0.9.4
- Windows 10 2004

**Comment by nschloe** [comment]
I cannot reproduce this.

**Comment by alexzhuustc** [comment]
Same issue.

if the function quit very quickly, the time spend may set to 0ns。 I guess this is a Windows-specific issue.

in perfplot/_main.py, 

            t0_ns = time.time_ns()
            val = kernel(data)
            t1_ns = time.time_ns()
            t_ns = t1_ns - t0_ns             **# t_ns may set to 0**

            repeat = remaining_time_ns // t_ns    **# divided by zero exception raised there**

**Comment by nschloe** [comment]
Let me see some minimal code for reproducing the error.

**Comment by SyedOmarNooredu** [comment]
Exact same as example/concat.py
`import numpy as np

import perfplot

perfplot.show(
    setup=np.random.rand,
    kernels=[
        lambda a: np.c_[a, a],
        lambda a: np.stack([a, a]).T,
        lambda a: np.vstack([a, a]).T,
        lambda a: np.column_stack([a, a]),
        lambda a: np.concatenate([a[:, None], a[:, None]], axis=1),
    ],
    labels=["c_", "stack", "vstack", "column_stack", "concat"],
    n_range=[2 ** k for k in range(15)],
    xlabel="len(a)",
)
`
Larger ranges don't have the issue though

**Comment by nschloe** [comment]
That's not minimal.

**Comment by SyedOmarNooredu** [comment]
```import numpy as np

import perfplot

perfplot.show(
    setup=np.random.rand,
    kernels=[
        lambda a: a*a,
        lambda a: a**2
    ],
    labels=["times", "power"],
    n_range=[2**k for k in range(15)],
    xlabel="len(a)",
)
```

**Comment by nschloe** [comment]
Do you need two kernels for this? Does your range need to go from 0 to 14?

**Comment by SyedOmarNooredu** [comment]
1. 2 kernels? what do you mean?
2. no, just used the concat.py values

**Comment by nschloe** [comment]
> 2 kernels? what do you mean?
```
    kernels=[
        lambda a: a*a,
        lambda a: a**2
    ],
```

> no, just used the concat.py values
Then make it minimal please.

**Comment by SyedOmarNooredu** [comment]
```
import numpy as np

import perfplot

perfplot.show(
    setup=np.random.rand,
    kernels=[
        lambda a: a*a,
    ],
    labels=["times"],
    n_range=[2**k for k in range(2)],
    xlabel="a",
)
```
this doesn't work either

**Comment by nschloe** [comment]
Make it smaller. You can do it!

**Comment by SyedOmarNooredu** [comment]
```
import numpy as np

import perfplot

perfplot.show(
    setup=np.random.rand,
    kernels=[
        lambda a: a,
    ],
    labels=["literally just a"],
    n_range=range(3),  # should always repeat experiments at least 3 times
    xlabel="a",
)
```

**Comment by set92** [comment]
Same problem, not sure if it helps, but the evaluation I tried was:

```python
import pandas as pd
import numpy as np
import perfplot

def make_df(n):
    possible_values = ['GOOD', 'BAD']
    df = pd.DataFrame(np.random.choice(possible_values, size=n), columns=['A'])
    return df

def saturdaysAIcode(x):
    investment_map = {'GOOD':1, 'BAD':0} 
    return x.applymap(lambda s: investment_map.get(s) if s in investment_map else s)

def possible_better_code(x):
    investment_map = {'GOOD':1, 'BAD':0}
    return x.replace(investment_map)

perfplot.show(
    setup=make_df,
    kernels=[saturdaysAIcode, possible_better_code],
    n_range=[2 ** k for k in range(2, 25)],
)
```

If I change the range lower limit to 17 it works, I suppose is because what they said, with big lower limits it never gets to 0? Not sure if there is someway to fix it.

**Comment by woctezuma** [comment]
I have tried https://github.com/nschloe/perfplot/issues/112#issuecomment-863101239 and https://github.com/nschloe/perfplot/issues/112#issuecomment-863110830 on Google Colab and both examples work perfectly fine.

```bash
# Update numpy to version 1.20 or higher
# Reference: https://stackoverflow.com/q/67117848/376454
%pip install -U numpy
```

```
%pip install perfplot
```

and then copy-pasting your examples. No issue whatsoever!

**Comment by SyedOmarNooredu** [comment]
Testing the solutions given (using concat program in README):
Solution #1 by @alexzhuustc ([Link](https://github.com/nschloe/perfplot/issues/112#issuecomment-862961184)): 61.7

> ```python
> t_ns = max(t1_ns - t0_ns, 1000*1000)
> ```
Graph matches one in README

Solution #2 by @set92 ([Link](https://github.com/nschloe/perfplot/issues/112#issuecomment-873284729)): 47.4 seconds

> ```python
> if t_ns == 0: t_ns = remaining_time_ns
> ```
>before the division

"before the division" meaning:
```python
            remaining_time_ns -= t_ns
            if t_ns == 0: t_ns = remaining_time_ns
            repeat = remaining_time_ns // t_ns
```
Graph matches one in README

Conclusion: @nschloe, either:
A) add one of these solutions to the code (preferably 2)
B) create another solution and add that to the code

**Comment by michal-demecki** [comment]
@nschloe root of the problem here is `time.time_ns()`. It does not provide accurate results e.g. due to Windows CPU optimizations. It's recommended to use `time.perf_counter_ns()` instead.

**Comment by nschloe** [comment]
@michal-demecki Good catch! Fixed in https://github.com/nschloe/perfplot/pull/128.
