### ISSUE TITLE
[BUG] Python3.7 incompatibility

### ISSUE THREAD

**Issue by FranzForstmayr** [nschloe/perfplot#121]
**Describe the bug**
Python3.7 incompatibility due to importing `Literal` from typing

**To Reproduce**
A _minimal_ example :)
```
import perfplot
```

**Diagnose**
I may ask you to cut and paste the output of the following command.
```
perfplot==0.9.8
```

Bug appeared in latest version (0.9.8)

**Comment by FranzForstmayr** [comment]
Just thinking about why this was not an issue in CI obviously...

**Comment by FranzForstmayr** [comment]
Is python3.9 used for every test in CI?
https://github.com/nschloe/perfplot/runs/3319490360#step:4:45

**Comment by nschloe** [comment]
Very good catch! Let me fix this real quick.

**Comment by nschloe** [comment]
Fixed by #123.
