### ISSUE TITLE
Programmatically determine version, a la `perfplot.__version__`

### ISSUE THREAD

**Issue by christian-cahig** [nschloe/perfplot#137]
Hi, this is a nice work. Just out of curiosity, is there a way to determine the version knowing only that I have imported perfplot? In most packages, we can do this with `package.__version__`; this is not available in perfplot.

**Comment by nschloe** [comment]
The modern way of doing this is via `importlib`, e.g.,
```python
from importlib import metadata

print(metadata.version("perfplot"))
```
```
0.9.13
``

**Comment by christian-cahig** [comment]
@nschloe thank you very much!
