### ISSUE TITLE
support multiple args

### ISSUE THREAD

**Issue by dizcza** [nschloe/perfplot#14]
Could you add support for multiple arguments like `lambda *args: ...`
```
perfplot.show(
        setup=lambda n: numpy.random.random_sample(size=(n, 128)),
        kernels=[
            lambda x, y: x + y
            ],
        n_range=[2**k for k in range(15)],
        xlabel='len(a)'
        )
```
TypeError: <lambda>() missing 1 required positional argument: 'y'

**Comment by dizcza** [comment]
Ok, I can broadcast all args to just `x`

**Comment by nschloe** [comment]
Indeed, that's what I'm doing as well.

**Comment by alisheikholeslam** [comment]
> Indeed, that's what I'm doing as well.

I have asked a related question on [SO](https://stackoverflow.com/questions/72768309/perfplot-to-compare-performance-of-several-functions-with-multiple-arguments-mo).
