### ISSUE TITLE
[REQUEST] specify y axis range

### ISSUE THREAD

**Issue by verhovsky** [nschloe/perfplot#144]
**How would you improve perfplot?**

I would like to do something like

```py
out = perfplot.bench(
    setup=lambda n: [0] + [1] * (n - 1),
    kernels=kernels,
    labels=labels,
    n_range=n_range,
    y_range=[10**-6, 10**-2],
    xlabel="my x-axis label",
)
```

**What problem does it solve~~d~~ for you?**

I am [generating two graphs with the same `n_range` and very similar timings](https://stackoverflow.com/questions/3844801/check-if-all-elements-in-a-list-are-identical/3844832#3844832) (because they are measuring the same algorithms against two different types of edge case inputs), so that when they come out, one graph goes from 10^-7 to 10^-3 while the second one goes from 10^-7 to 10^-2. This makes the graphs slightly misleading and harder to read when I display them side by side, so I would like a way to manually specify the range.

**Comment by nschloe** [comment]
You can do that with
```
plt.ylim([25, 50])
```

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time!
