### ISSUE TITLE
[BUG] Wrong results for `iter`

### ISSUE THREAD

**Issue by Harmouch101** [nschloe/perfplot#145]
**Describe the bug**

I ran some benchmarks on the iter function, and the results don't align with what is expected. Like lists, searching for an item in an `iterator` should be in linear time O(n). However, `perfplot` shows that it is O(1). At some point, when the list gets larger, it shows logical behavior O(n).

![Figure_10](https://user-images.githubusercontent.com/62179149/172038493-0a67788a-82b0-41a4-baea-2256848a0c9f.png)

**To Reproduce**

```python
import random
import perfplot

def setup(n):
    data = list(range(n))
    random.shuffle(data)
    dict_array = {x:i for i, x in enumerate(data)}
    return data, set(data), iter(data), dict_array

def list_in(*args):
    return -99 in args[0]

def set_in(*args):
    return -99 in args[1]

def iter_in(*args):
    return -99 in args[2]

def dict_in(*args):
    return -99 in args[3]

def convert_list_to_set(*args):
    return set(args[0])

def convert_list_to_iter(*args):
    return iter(args[0])

def convert_list_to_dict(*args):
    return {x:i for i, x in enumerate(args[0])}


b = perfplot.bench(
    setup=setup,
    kernels=[
        list_in,
        set_in,
        iter_in,
        dict_in,
        convert_list_to_set,
        convert_list_to_iter,
        convert_list_to_dict,
    ],
    n_range=[2 ** k for k in range(1, 25)],
    xlabel="length of the list.",
    equality_check= None
)

b.show()

```

**Diagnose**

```
perfplot==0.10.2
```

At first, I thought the problem could be with the `equality_check= None` parameter. So, I removed it and tried to benchmark the iter function alone. It results in the same behaviors.

![Figure_12](https://user-images.githubusercontent.com/62179149/172038501-0e2f6b70-4295-4827-b827-d8067191adb2.png)

`list` and `iter` should give the same O(N) as runtime. Perhaps `list` is slightly faster.

**Comment by nschloe** [comment]
What makes you think this is wrong? Can you confirm with some `timeit` times?

**Comment by Harmouch101** [comment]
In theory, the only way to find an element in an iterator is by consuming elements and checking. In other words, invoking `__next__` on the iterator and then an if statement which means a linear runtime O(n). That's my understanding of how iterators work unless there is some wizard logic that can tell if an element exists in an iterator in O(1), like voila! The element exists in an iterator. But I don't think it is O(1), like a hashmap and such.

However, running `timeit` shows the following results for the first 9 iterations:

```sh

#  Obj  Size      Time           Obj  Size      Time
0. list 10        3.5e-07    |   iter 10        6.1e-07    |   
1. list 20        5.9e-07    |   iter 20        8.3e-07    |   
2. list 40        1.3e-06    |   iter 40        1.6e-06    |   
3. list 80        2.8e-06    |   iter 80        3.5e-06    |   
4. list 160       5.5e-06    |   iter 160       6.6e-06    |   
5. list 320       1.1e-05    |   iter 320       7.9e-06    |   
6. list 640       1.6e-05    |   iter 640       1.9e-05    |   
7. list 1280      3.3e-05    |   iter 1280      3.8e-05    |   
8. list 2560      6.5e-05    |   iter 2560      7.6e-05    |   
```

Both list and iter have pretty much identical runtime, O(n), as `timeit` shows, unlike perfplot. This confirms my hypothesis that there is a glitch in the simulation. I mean a bug in `perfplot`.

**Code**:

```python
from timeit import Timer

print("#  Obj  Size      Time           Obj  Size      Time")
for iteration in range(25):
    size = 10 * 2 ** iteration
    if size < 1000:
        number = 200_000
    elif size < 10_000:
        number = 20_000
    elif size < 100_000:
        number = 2000
    elif size < 1_000_000:
        number = 200
    else:
        number = 20
    print(f"{iteration:.<2}", end=' ')
    for name, snippet in [("list", "-99 in list_"), ("iter", "-99 in iter(list_)")]:
        T = Timer(snippet, (lambda n: f"list_ = list(range({n}))")(size))
        best = min(T.repeat(number=number, repeat=7))
        print(f"{name} {size:<8}  {(best/number):1.2g}", end='    |   ')
    print()
```

**Comment by Harmouch101** [comment]
Thanks for the tool, BTW. It allows me to make some crazy scientific stuff and share my results on Twitter, like this one:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Efficient Python: Day-05<br><br>Did you know that using a simple plus operator is the fastest approach to concatenate two strings of equal length?<br><br>concat_strings = string1 + string2<a href="https://twitter.com/hashtag/python?src=hash&amp;ref_src=twsrc%5Etfw">#python</a> <a href="https://twitter.com/hashtag/100DaysOfCode?src=hash&amp;ref_src=twsrc%5Etfw">#100DaysOfCode</a> <a href="https://twitter.com/hashtag/Python3?src=hash&amp;ref_src=twsrc%5Etfw">#Python3</a> <a href="https://t.co/i02XG1VY6k">pic.twitter.com/i02XG1VY6k</a></p>&mdash; Mahmoud (@LBx86) <a href="https://twitter.com/LBx86/status/1532718445699207169?ref_src=twsrc%5Etfw">June 3, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by nschloe** [comment]
I got this
```python
In [24]: it = iter(range(10))

In [25]: %timeit (-1 in it)
35.6 ns ± 0.0944 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [26]: it = iter(range(100))

In [27]: %timeit (-1 in it)
35.2 ns ± 0.0736 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [28]: it = iter(range(1000))

In [29]: %timeit (-1 in it)
35.2 ns ± 0.0409 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [30]: it = iter(range(10000))

In [31]: %timeit (-1 in it)
35.5 ns ± 0.223 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [32]: it = iter(range(100000))

In [33]: %timeit (-1 in it)
35.4 ns ± 0.5 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [34]: it = iter(range(1000000))

In [35]: %timeit (-1 in it)
35.3 ns ± 0.118 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [36]: it = iter(range(10000000))

In [37]: %timeit (-1 in it)
235 ns ± 305 ns per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by nschloe** [comment]
I think you measure the `iter()` construction which in my example is in the setup.

**Comment by Harmouch101** [comment]
You are absolutely right. I have updated the code above. Now, it shows a constant lookup time for lists that contains ~ 10**6 elements which begs the question: how in the world is it even possible with `iter`? How is it implemented at a low level? This proves that the fastest approach to find an item within a list is by converting it into an iterator. Interesting! If you have any explanation whatsoever for this sort of behavior, lemme know. For me, It seems like some kind of Egyptian magic.

**Comment by Harmouch101** [comment]
I am going to close this issue. I am looking forward to your explanation of this strange behavior.

**Comment by nschloe** [comment]
I'm looking forward to _yours_!

**Comment by nschloe** [comment]
I'd post on a Python mailing list.

**Comment by Harmouch101** [comment]
I have figured out the reason. `timeit` was measuring a `StopIteration` after the first iteration, which is actually negligible compared to the first iteration.

We can write a handy script to help us understand what `timeit` was trying to accomplish:

```python
import time
list_ = list(range(10**3))
iter_ = iter(list(range(10**3)))
list_time_samples = []
iter_time_samples = []
for _ in range(100):
  start = time.perf_counter_ns()
  _ = -99 in list_
  end = time.perf_counter_ns()
  list_time_samples.append(end - start)
for _ in range(100):
  start = time.perf_counter_ns()
  _ = -99 in iter_
  end = time.perf_counter_ns()
  iter_time_samples.append(end - start)

print(sum(list_time_samples)/100, sum(iter_time_samples)/100, sep="\n")
print(list_time_samples)
print(iter_time_samples)
```

**Output**:

```python
34764.78
1168.4

[35515, 34760, 34533, 34492, 34469, 34580, 34513, 34432, 34577, 34493, 34635, 34612, 34484, 34422, 34440, 34499, 34469, 34536, 34446, 34487, 34469, 34470, 34482, 34476, 34680, 34476, 34475, 34430, 34489, 34436, 34480, 34482, 34480, 34483, 34489, 34429, 34440, 34436, 34475, 34583, 34426, 34476, 34473, 34480, 34423, 34526, 34593, 34642, 34492, 34497, 34476, 34567, 39331, 34473, 34690, 34486, 34467, 34475, 34484, 34513, 34577, 34463, 34530, 34479, 34422, 34480, 34472, 34435, 34473, 34432, 34476, 55074, 34596, 34489, 34500, 34623, 34482, 34459, 34483, 34496, 34697, 34459, 34436, 34443, 34489, 34483, 34495, 34600, 34670, 34477, 34479, 34480, 34482, 34470, 34489, 34484, 34439, 34485, 34487, 34449]

[55691, 831, 611, 642, 644, 605, 618, 612, 609, 602, 604, 645, 608, 604, 608, 646, 618, 614, 605, 597, 621, 612, 607, 614, 612, 601, 608, 615, 608, 609, 611, 615, 602, 619, 601, 607, 606, 668, 652, 618, 588, 608, 606, 619, 608, 609, 614, 642, 638, 612, 601, 611, 612, 602, 608, 612, 615, 601, 602, 611, 648, 604, 678, 612, 604, 604, 609, 604, 621, 605, 618, 632, 608, 602, 611, 652, 621, 571, 605, 607, 652, 602, 614, 612, 612, 601, 601, 656, 614, 615, 627, 609, 605, 691, 604, 629, 614, 607, 612, 608]
```

So, we can only compare the results for the first iteration, cause after that one, the iterator will throw a `StopIteration` exception each time the program tries to execute the `__next__` method which results in lookup time being ~zero.

**Key takeaway**:

* A list is slightly faster than an iterator.
* We can't compute the average lookup time for an iterator. The only way to do so is by creating a new iterator each time we try to measure the time for element lookup, which will include the list to iter conversion.

**Comment by nschloe** [comment]
I see! Thanks for digging this up.
