### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by BielStela** [nschloe/perfplot#34]
Hi, awesome work! 
but I found it a bit confusing at the beginning. For example, it would be nice to have an example with more than one argument like this workaround:

```python
out = perfplot.bench(
    setup=lambda n: make_data(n),
    kernels=[
        lambda a: _split_data(*a, 3),
        lambda a: _split_data_pd(*a, 3),
        ],
    labels=['numpy', 'pandas'],
    n_range=[2**k for k in range(1,25)],
    xlabel='N',
    logx=True,
    logy=True,
    equality_check=None,
    automatic_order=False
    )
```
here `make_data()` returns a tuple and then I unpack it with `*` for the sequence of args. It would be more straight forward If the relation between the lambdas is more documented or have extra examples with multiple arguments etc. I can do it if you think is a good idea.

Thanks for doing this

**Comment by nschloe** [comment]
I've improved the documentation a little bit, but I think this particular case is a little too specific. If anyone else hits this in the future, please comment here, I'll think about cooking something up then.
