### ISSUE TITLE
Errorbar support

### ISSUE THREAD

**Issue by dizcza** [nschloe/perfplot#39]
Please, add support for errorbars, evaluated across trials for fixed input size.

**Comment by nschloe** [comment]
Not sure what you mean by "error".

**Comment by dizcza** [comment]
Some functions might have different running time from sample to sample. So by error I mean standard deviation of the running time.

**Comment by nschloe** [comment]
> Some functions might have different running time from sample to sample.

Ah, I see.

Contrary to what one may think at first, average and standard deviation are typically not interesting when measuring a certain operation a thousand times. The only interesting value is the _minimum_ time; it tells you how fast your computer can run that piece of code. The reason why it's not always that fast is that the computer does other things in the background -- networking, rendering, whatever -- and when measuring the average and standard deviation, you're really only measuring how much your computer is slowed down by that. It's got nothing to do with the code you're running.
