### ISSUE TITLE
Set python_requires

### ISSUE THREAD

**Issue by lycantropos** [nschloe/perfplot#59]
Since code uses `f`-strings, which available [from *Python3.6*](https://docs.python.org/3/whatsnew/3.6.html), it should be reasonable to specify that by `python_requires='>=3.6'` in [`setup.py`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires), so it won't install on earlier versions (or use `str.format` maybe).

**Comment by nschloe** [comment]
Thanks, fixed now.
