### ISSUE TITLE
feature request: monospace font for labels

### ISSUE THREAD

**Issue by verhovsky** [nschloe/perfplot#90]
I'm using perfplot to time small code samples. Instead of giving each sample a name and having to think about which name refers to which code, I put the sample (or its essence) as the label. It would be nice if I could draw those labels in monospace.

**Comment by verhovsky** [comment]
Nevermind, I think you can already do this with

```python
out = perfplot.bench(
    # ...
)
out.show()
out.save("perf.png", family="monospace")
```

**Comment by nschloe** [comment]
Can't you already do that like:
```python
import matplotlib

matplotlib.rc('font', family="monospace")
```
See [here](https://matplotlib.org/stable/tutorials/text/text_props.html).
